services:
  web:
    build: .
    # Arranca el servidor Django en modo desarrollo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    # Si usas SQLite, no necesitas otro servicio de BD.
